version: "3.6"
services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      # The location of the RabbitMQ server.  "amqp" is the protocol;
      # "rabbitmq" is the hostname.  Note that there is not a guarantee
      # that the server will start first!  Telling the pika client library
      # to try multiple times gets around this ordering issue.
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    volumes:
      - thesisRabbitVolume:/var/lib/rabbitmq
  postgres:
    image: postgres:12.2-alpine
    restart: always
    volumes:  
      - thesisPostgresVolume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

  netor_coordinator:
    build: ./coordinator
    restart: always
    ports:
      - '5000:5000'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "postgres"
      POSTGRES_DB: "vsLCM"
      POSTGRES_IP: postgres
      APP_SECRET: "tenantManager"
      RABBIT_USER: "admin"
      RABBIT_PASS: "admin"
      RABBIT_IP: rabbitmq
      IDP_IP: netor_tenant

  netor_domain:
    build: ./domain
    restart: always
    ports:
      - '5001:5001'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "postgres"
      POSTGRES_DB: "vsDomain"
      POSTGRES_IP: postgres
      APP_SECRET: "tenantManager"
      RABBIT_USER: "admin"
      RABBIT_PASS: "admin"
      RABBIT_IP: rabbitmq
      IDP_IP: netor_tenant

  netor_manager:
    build: ./manager
    restart: always
    ports:
      - '5555:5555'
    environment:
      APP_SECRET: "tenantManager"
      RABBIT_USER: "admin"
      RABBIT_PASS: "admin"
      RABBIT_IP: rabbitmq

  netor_placement:
    build: ./placement
    environment:
      RABBIT_USER: "admin"
      RABBIT_PASS: "admin"
      RABBIT_IP: rabbitmq

  netor_tenant:
    build: ./tenant
    restart: always
    ports:
      - '5002:5002'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "postgres"
      POSTGRES_DB: "vsTenant"
      POSTGRES_IP: postgres
      APP_SECRET: "tenantManager"
      RABBIT_USER: "admin"
      RABBIT_PASS: "admin"
      RABBIT_IP: rabbitmq
volumes:
  thesisPostgresVolume:
    external: false
  thesisRabbitVolume:
    external: false