netslice-subnet:
- id: interdomain-ns_1
  additionalParamsForVnf:
  - member-vnf-index: "1"
    additionalParams:
      tunnel_address: "10.0.0.1/24"
      tunnel_id: "1"
      ns_id: "interdomain-ns_1"
      vnf_id: "1"
- id: interdomain-ns_2
  additionalParamsForVnf:
  - member-vnf-index: "1"
    additionalParams:
      tunnel_address: "10.0.0.2/24"
      tunnel_id: "2"
      ns_id: "interdomain-ns_2"
      vnf_id: "1"