version: "3"
services:
  mock:
    build: ./mock
    ports:
      - "8082:8082"
  portal:
    depends_on:
      - mock
    build: .
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - "/app/node_modules"
      - ".:/app"